services:
  gpt4free_bot:
    container_name: gpt4free_bot
    image: gpt4free_bot
    restart: unless-stopped
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - AUTHORIZED_USER_ID=${AUTHORIZED_USER_ID}
    volumes:
      - ./bot.log:/app/bot.log
      - ./history.db:/app/history.db