services:
  free_bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - AUTHORIZED_USER_ID=${AUTHORIZED_USER_ID}
    volumes:
      - ./bot.log:/app/bot.log
      - ./history.db:/app/history.db